% Description:
%     DO NOT change the VALUES of this file!
%     This file is generated by genCaseList.m automatically.
% 
%     Generated Date: 11-Jul-2018 10:37:01
%  Copyright, 2018, H.B. Zhang, <hongbo.zhang83@gmail.com>

% parameter values: Run genCaseList.m to gen case_list.m after modified the .xlsx file
clear caseList;

parval={
%	fBaud   	modFormat	Nb      	Nsc     	Nsceff  	Nf      	CP      	SNR     	isEqualization	isDHTON 
	30      	'QPSK'  	2       	256     	248     	100     	0.25    	15      	1       	0       ;
	60      	'QPSK'  	2       	256     	248     	200     	0.25    	25      	1       	1       ;
	40      	'16QAM' 	2       	256     	248     	200     	0.25    	25      	1       	1       ;

};

% parameter string
parstr = { 'fBaud','modFormat','Nb','Nsc','Nsceff','Nf','CP','SNR','isEqualization','isDHTON'};
caseList  = cell2struct(parval,parstr,2);
